services:
  db_test:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: password_test
      POSTGRES_DB: db_test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_restapi
    environment:
      DATABASE_URL: postgresql+psycopg2://user_test:password_test@db_test/db_test
    ports:
      - "8000:8000"
    depends_on:
      - db_test
    networks:
      - app_network

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migrate
    environment:
      DATABASE_URL: postgresql+psycopg2://user_test:password_test@db_test/db_test
    command: [ "alembic", "upgrade", "head" ]
    depends_on:
      - db_test
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
